### PR TITLE
Update FAudio to 21.11

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
We should upgrade it on next release, I'll add it to the 2021.10.28 project, thanks! Keep the PR open.

**Comment by mirkobrombin** [comment]
There are some problem building the latest FAudio 21.10. I don't have time to invest in diagnosing the problem, I think we will stay on 21.10 for the next release.

**Comment by LeandroStanger** [comment]
bot, build

**Comment by mirkobrombin** [comment]
Closing as this update break a lot of things. Checking on next release.

**Pull request closed without merging**
