### PR TITLE
For optical drive access

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build

**Comment by LeandroStanger** [comment]
An image from my test to prove it works
Captura de tela de 2021-03-07 10-34-43

**Comment by mirkobrombin** [comment]
Nice I'm going to push. Btw good distro EndlessOS

**Comment by tim77** [comment]
You seriously traded between isolation, especially in such thing like Wine where is most important, for useless optical drive access support?

**Comment by mirkobrombin** [comment]
Permissions were initially limited to specific paths. I am not in favor of using the whole host filesysten but I do not even have the correct knowledge of Flatpak to act. I let the conversation go and accept your verdict.

**Comment by mirkobrombin** [comment]
This can actually be a system security nightmare. I have reverted the changes but I leave this discussion free to proceed in case it is necessary to proceed differently.

Users who require more access can still use apps like Flatseal to extend the permissions level of the Flatpak.

**Comment by tim77** [comment]
> but I do not even have the correct knowledge of Flatpak to act.

@mirkobrombin yep, i am not blame or something. But there was no justification for @LeandroStanger who using flatpak for years and still doing such things. Maybe he just don't understand what he doing maybe this intentional, i don't know and time to bump this [thread](https://github.com/flathub/flathub/issues/1337) again and there should strict politics about post changing permissions especially like that. At least such update should allowed after flathub admin review.

**Comment by gasinvein** [comment]
@mirkobrombin Just `--filesystem=/run/media` and `--filesystem=/media` should do for optical drives. These are respectively modern and legacy default path for dynamic mount points created automatically by UDisks2 for removable media.

**Comment by gasinvein** [comment]
@mirkobrombin Speaking of UDisks2, you may want to add `--system-talk-name=org.freedesktop.UDisks2`. AFAIK Wine uses  UDisks2 to enumerate drives if built with DBus support, so some Windows installers may break if Wine can't access UDisks2 bus name.
This shouldn't be a big security hole, since UDisks2 prompts user authentication via polkit for most operations anyway (unless host OS is configured otherwise).

**Pull request merged**
