### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
It looks like that the Python dependencies (com.usebottles.bottles.pypi-deps.yaml) will also need updating.

@TheEvilSkeleton @koplo199 Could you take a look at this? Thanks!

**Comment by mirkobrombin** [comment]
> It looks like that the Python dependencies (com.usebottles.bottles.pypi-deps.yaml) will also need updating.
> 
> @TheEvilSkeleton @koplo199 Could you take a look at this? Thanks!

Both is no more in the Bottles team. We are already testing some updates.

**Comment by AsciiWolf** [comment]
Ah, I was not aware that he left. Sorry!

**Comment by koplo199** [comment]
Relevant PR: https://github.com/bottlesdevs/Bottles/pull/3099
The manifest **must not** be fiddled with here, It is updated in the [Bottles](https://github.com/bottlesdevs/Bottles/blob/main/com.usebottles.bottles.yml) repository and then automatically kept in sync by the CI.

**Pull request closed without merging**
