### PR TITLE
Add FEDC support

### PR DESCRIPTION
**Pull request by tim77**
Bot will send you PR's with updates automatically. This could save your time.

More info: https://github.com/flathub/flatpak-external-data-checker

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Amazing, so the bot will automatically create new PR for new Bottles releases?

**Comment by tim77** [comment]
Yep. Maybe also nice to do this for `beta` branch as well. But **Flathub** bot will send automatically PR's only for primary branch which is `master`. So for `beta` we need to write custom GH Actions for FEDC or just invoke it manually in CLI:

```bash
flatpak run org.flathub.flatpak-external-data-checker --update MANIFEST_FILE
```

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
Sorry, I was testing something. Move along…

**Comment by mirkobrombin** [comment]
> Yep. Maybe also nice to do this for `beta` branch as well. But **Flathub** bot will send automatically PR's only for primary branch which is `master`. So for `beta` we need to write custom GH Actions for FEDC or just invoke it manually in CLI:
> 
> ```shell
> flatpak run org.flathub.flatpak-external-data-checker --update MANIFEST_FILE
> ```

Awesome! This definitely save a lot of time :D Can I merge this safely?

**Comment by tim77** [comment]
I hope so. Current for `master` branch is trivial. Bot will send within an hour PR next time when you will release new version

**Comment by mirkobrombin** [comment]
> I hope so. Current for `master` branch is trivial. Bot will send within an hour PR next time when you will release new version

Let's see haha

**Pull request merged**
